### ISSUE TITLE
TypeError: Cannot read property 'regexp' of undefined

### ISSUE THREAD

**Issue by nerdoc** [Kagami/jade-pages-brunch#5]
I occassionally get errors like these when compiling - and I don't really recognized why - **and**, I can't find a reason.
There has been a [bug in sass-brunch](https://github.com/es128/progeny/issues/9) which looks similar, but I don't use sass-brunch, and the error occurs in jade-pages-brunch.
```
/home/.../node_modules/jade-pages-brunch/node_modules/progeny/lib/index.js:168
      regexp = def.regexp;
                  ^
TypeError: Cannot read property 'regexp' of undefined
  at JadePages.progeny [as getDependencies] (/home/.../node_modules/jade-pages-brunch/node_modules/progeny/lib/index.js:168:19)
  at getDependencies (/usr/local/lib/node_modules/brunch/lib/fs_utils/pipeline.js:40:23)
  at /usr/local/lib/node_modules/brunch/lib/fs_utils/pipeline.js:80:16
  at JadePages.module.exports.JadePages.compile (/home/.../node_modules/jade-pages-brunch/lib/index.js:99:9)
  at /usr/local/lib/node_modules/brunch/lib/fs_utils/pipeline.js:96:31
  at fn (/usr/local/lib/node_modules/brunch/node_modules/async-waterfall/index.js:19:24)
  at Object._onImmediate (/usr/local/lib/node_modules/brunch/node_modules/async-waterfall/index.js:58:22)
  at processImmediate [as _immediateCallback] (timers.js:336:15)
```
my brunch-config:
```
exports.config =
  # See http://brunch.io/#documentation for docs.
  conventions:
    assets: /^app\/assets\//
  files:
    javascripts:
      joinTo:
        'data/js/vendor.js': /^bower_components|vendor\/scripts/
        'data/js/app.js': /^app\/scripts/
    stylesheets:
      joinTo:
        'data/app.css': /^app\/styles/
    templates:
      joinTo:
        'data/app.js'

  plugins:
    jadePages:
      # ignore files starting with '_'
      pattern: /^app\/[^_].*\.jade$/
      htmlmin: false
```
