### ISSUE TITLE
htmlmin: false ignored

### ISSUE THREAD

**Issue by githistory** [Kagami/jade-pages-brunch#8]
Below is my code for production build, the html is always minified whatever I set htmlmin option to.

```
  overrides:
    production:
      plugins:
        jadePages:
          htmlmin: false
```

**Comment by Kagami** [comment]
Hi. I think that's not minification, but default jade output. Add `jade: pretty: true` if you want to see formatted output.

**Comment by Kagami** [comment]
Though now it's always overriden to be `false` in optimize mode. But it's not html minification, I've just checked. Do you want to pass `pretty: true` in production mode too?

**Comment by githistory** [comment]
I actually tried ```pretty: true```. Still, no luck. Here's my config:

```
  overrides:
    production:
      plugins:
        jadePages:
          jade: pretty: true
          htmlmin: false
```

**Comment by githistory** [comment]
Just experimented a bit. Indeed it's due to ```pretty``` always being set to ```false``` in optimize mode.

Guess it'd be good to be able to override that option. Something along the lines of

```
      if (optimize && !_.isBoolean(this.jadeOptions.pretty)) {
        this.jadeOptions.pretty = false;
      }
```

What would you think?

**Comment by githistory** [comment]
Just noticed your source is in coffee. Then great!

```
if optimize
      # We don't want redundant whitespaces for product version, right?
      # Sometimes we do though...
      @jadeOptions.pretty ?= false
```

**Comment by Kagami** [comment]
Fixed, thanks.

**Comment by githistory** [comment]
My pleasure to help!

I just noticed something else in your commit though:

```
else if _.isObject(htmlminConfig)
  @htmlmin = true
  @htmlminOptions = _.extend({}, htmlminConfig)
```

This is saying, if ```htmlminConfig``` is an object then use it as options. Then the following defaults are not applied at all:

```
DEFAULT_HTMLMIN_OPTIONS:
    removeComments: true
    removeCommentsFromCDATA: true
    removeCDATASectionsFromCDATA: true
    collapseBooleanAttributes: true
    useShortDoctype: true
    removeEmptyAttributes: true
    removeScriptTypeAttributes: true
    removeStyleLinkTypeAttributes: true
```
